apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "resilio.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "resilio.name" . }}
    helm.sh/chart: {{ include "resilio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "resilio.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "resilio.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.volumes.enabled }}
      volumes:
        - name: resilio-data
          persistentVolumeClaim:
            claimName: resilio-data-claim
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: portui
              containerPort: {{ .Values.service.portui }}
              protocol: TCP
            - name: portsync
              containerPort: {{ .Values.service.portsync }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: portui
          readinessProbe:
            tcpSocket:
              port: portui
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- if .Values.volumes.enabled }}
          volumeMounts:
            - name: resilio-data
              mountPath: /mnt/sync
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
