apiVersion: v1
kind: Service
metadata:
  name: {{ include "resilio.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "resilio.name" . }}
    helm.sh/chart: {{ include "resilio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portui }}
      targetPort: portui
      protocol: TCP
      name: http
    - port: {{ .Values.service.portsync }}
      targetPort: portsync
      protocol: TCP
      name: sync 
  selector:
    app.kubernetes.io/name: {{ include "resilio.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
